/export/home/jeffrey/Documents/sv-benchmarking/workflow/sv_calling_dir/.snakemake/conda/f17c13b68665fe91b47eb3833fa04da5_/lib/python3.12/site-packages/joblib/parallel.py:1362: UserWarning: The backend class 'SequentialBackend' does not support timeout. You have set 'timeout=99999' in Parallel but the 'timeout' parameter will not be used.
  warnings.warn(
[M::main_ropebwt2] inserted 1504868708 symbols in 91.532 sec, 269.824 CPU sec
[M::main_ropebwt2] constructed FM-index in 100.605 sec, 275.448 CPU sec
[M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (10099790, 406983793, 340400666, 340400666, 406983793, 0)
[M::main_ropebwt2] rld: (tot, $, A, C, G, T, N) = (1504868708, 10099790, 406983793, 340400666, 340400666, 406983793, 0)
[M::main] Version: r187
[M::fm6_unitig] choose prime 123457
[M::main] CMD: ropebwt2 -dNCr ../../outputs/tiddit/HG002.bwa-mem2.tiddit_tiddit/clips.fa
[M::main] Real time: 107.325 sec; CPU: 281.844 sec
[M::main] Version: r178
[M::main] CMD: fermi2 assemble -t 1 -l 81 -
[M::main] Real time: 1803.350 sec; CPU: 1676.116 sec
Traceback (most recent call last):
  File "/export/home/jeffrey/Documents/sv-benchmarking/workflow/sv_calling_dir/.snakemake/conda/f17c13b68665fe91b47eb3833fa04da5_/bin/tiddit", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/export/home/jeffrey/Documents/sv-benchmarking/workflow/sv_calling_dir/.snakemake/conda/f17c13b68665fe91b47eb3833fa04da5_/lib/python3.12/site-packages/tiddit/__main__.py", line 161, in main
    tiddit_contig_analysis.main(prefix,sample_id,library,contigs,coverage_data,args)
  File "tiddit/tiddit_contig_analysis.pyx", line 134, in tiddit.tiddit_contig_analysis.main
  File "tiddit/tiddit_contig_analysis.pyx", line 11, in tiddit.tiddit_contig_analysis.read_contigs
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 956, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
